//Fibonacci number is generated by adding the previous two numbers- F(n)= f(n-1)+f(n-2).... 

class FibonacciSeries {
    public static void main(String[] args) {
        int n = 10;
        System.out.println(fib(n));
    }
    public static int fib(int n){
        if (n <= 1)
        return n;
        return fib(n-1) + fib(n-2);
    }

}
